export const clerkDarkAppearance = {
  variables: {
    colorBackground: "#18181b",
    colorInputBackground: "#27272a",
    colorText: "#fafafa",
    colorTextSecondary: "#a1a1aa",
    colorTextOnPrimaryBackground: "#ffffff",
    colorPrimary: "#d97706",
    colorDanger: "#f87171",
    colorSuccess: "#34d399",
    colorNeutral: "#71717a",
    colorInputText: "#fafafa",
    borderRadius: "0.875rem",
    fontFamily: "inherit",
    fontSize: "14px",
  },
  elements: {
    // Sign-in/up card
    card: "shadow-none",
    cardBox: "shadow-none",
    headerTitle: "text-white font-bold tracking-tight",
    headerSubtitle: "text-zinc-400",
    socialButtonsBlockButton: "border-zinc-700/60 bg-zinc-800/80 hover:bg-zinc-800 text-zinc-200",
    socialButtonsBlockButtonText: "font-medium text-zinc-200",
    dividerLine: "bg-zinc-800",
    dividerText: "text-zinc-500",
    formFieldLabel: "text-zinc-400 text-xs font-medium",
    formFieldInput: "rounded-xl",
    formButtonPrimary: "rounded-xl font-semibold shadow-none",
    footerActionText: "text-zinc-500",
    footerActionLink: "text-amber-400 hover:text-amber-300 font-medium",
    alertText: "text-red-300",

    // UserButton popover
    userButtonPopoverCard: "rounded-2xl",
    userPreviewMainIdentifier: "text-zinc-100 font-semibold",
    userPreviewSecondaryIdentifier: "text-zinc-400",
    userButtonPopoverActionButton: "text-zinc-200 rounded-xl",
    userButtonPopoverActionButtonText: "text-zinc-200 font-medium",
    userButtonPopoverActionButtonIcon: "text-zinc-500",
    userButtonPopoverFooter: "hidden",
    avatarBox: "rounded-full",
  },
};
